SELECT
      S.SHIPMENT_XID
	, R.SHIPMENT_REFNUM_VALUE AS "BOL"
	, STC.SHIPMENT_REFNUM_VALUE AS "CASS_SENT"
	, LD.SHIPMENT_REFNUM_VALUE AS "PORT_OF_LOADING"
	, DIS.SHIPMENT_REFNUM_VALUE AS "PORT_OF_DISCHARGE"
	, RCP.SHIPMENT_REFNUM_VALUE AS "PLACE_OF_RECEIPT"
	, DLV.SHIPMENT_REFNUM_VALUE AS "PLACE_OF_DELIVERY"
	, E.EQUIPMENT_INITIAL_NUMBER
	, EA.EQUIPMENT_ATTRIBUTE_VALUE AS "DIVERTED"
	, EB.EQUIPMENT_ATTRIBUTE_VALUE AS "CTN_BOL"
	, ED.EQUIPMENT_ATTRIBUTE_VALUE AS "CTN_DIV_BOL"
	, SSLP.INVOLVED_PARTY_CONTACT_GID AS "SSL_PICKUP"
	, SSLD.INVOLVED_PARTY_CONTACT_GID AS "SSL_DROPOFF"
        , ST.ACTUAL_ARRIVAL
	


FROM [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] R
JOIN [GLOGOWNERNA04PRD].[SHIPMENT_T] S
ON R.SHIPMENT_GID = S.SHIPMENT_GID
AND R.SHIPMENT_REFNUM_QUAL_GID = 'ILS.BILL_OF_LADING_NUMBER'
AND S.TRANSPORT_MODE_GID LIKE '%ILS.OCEAN%' 
JOIN GLOGOWNERNA04PRD.SHIPMENT_STOP_T ST
ON S.SHIPMENT_GID = ST.SHIPMENT_GID
    AND ST.STOP_NUM = '2'
LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_S_EQUIPMENT_JOIN_T] A
ON R.SHIPMENT_GID = A.SHIPMENT_GID
LEFT JOIN [GLOGOWNERNA04PRD].[S_EQUIPMENT_T] E
ON A.S_EQUIPMENT_GID = E.S_EQUIPMENT_GID
LEFT JOIN [GLOGOWNERNA04PRD].[S_EQUIPMENT_ATTRIBUTE_T] EA
ON E.S_EQUIPMENT_GID = EA.S_EQUIPMENT_GID
AND EA.EQUIPMENT_ATTRIBUTE_QUAL_GID LIKE '%ILS.CONTAINER_DIVERTED%'

LEFT JOIN [GLOGOWNERNA04PRD].[S_EQUIPMENT_ATTRIBUTE_T] EB
ON E.S_EQUIPMENT_GID = EB.S_EQUIPMENT_GID
AND EB.EQUIPMENT_ATTRIBUTE_QUAL_GID LIKE '%ILS.BILL_OF_LADING_NUMBER%'

LEFT JOIN [GLOGOWNERNA04PRD].[S_EQUIPMENT_ATTRIBUTE_T] ED
ON E.S_EQUIPMENT_GID = ED.S_EQUIPMENT_GID
AND ED.EQUIPMENT_ATTRIBUTE_QUAL_GID LIKE '%ILS.DIVERTED BILL OF LADING%'

LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] STC
ON R.SHIPMENT_GID = STC.SHIPMENT_GID
AND STC.SHIPMENT_REFNUM_QUAL_GID LIKE '%CASS_SENT_DATE%'

LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] DIS
ON R.SHIPMENT_GID = DIS.SHIPMENT_GID
AND DIS.SHIPMENT_REFNUM_QUAL_GID LIKE '%PORT_OF_DISCHARGE%'

LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] LD
ON R.SHIPMENT_GID = LD.SHIPMENT_GID
AND LD.SHIPMENT_REFNUM_QUAL_GID LIKE '%PORT_OF_LOADING%'

LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] RCP
ON S.SHIPMENT_GID = RCP.SHIPMENT_GID
AND RCP.SHIPMENT_REFNUM_QUAL_GID LIKE '%PLACE_OF_RECEIPT%'

LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] DLV
ON S.SHIPMENT_GID = DLV.SHIPMENT_GID
AND DLV.SHIPMENT_REFNUM_QUAL_GID LIKE '%PLACE_OF_DELIVERY%'

LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_INVOLVED_PARTY_T] SSLP
ON S.SHIPMENT_GID = SSLP.SHIPMENT_GID
AND SSLP.INVOLVED_PARTY_QUAL_GID LIKE 'ILS.SSL_PICKUP'

LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_INVOLVED_PARTY_T] SSLD
ON S.SHIPMENT_GID = SSLD.SHIPMENT_GID
AND SSLD.INVOLVED_PARTY_QUAL_GID LIKE 'ILS.SSL_DROPOFF'

WHERE SUBSTRING(S.DEST_LOCATION_GID, 6, 2) in ('US', 'MX', 'CA')