SELECT
      S.SHIPMENT_XID
	, R.SHIPMENT_REFNUM_VALUE AS "BOL"
	, STC.SHIPMENT_REFNUM_VALUE AS "CASS_SENT"
	, LD.SHIPMENT_REFNUM_VALUE AS "PORT_OF_LOADING"
	, DIS.SHIPMENT_REFNUM_VALUE AS "PORT_OF_DISCHARGE"
	, RCP.SHIPMENT_REFNUM_VALUE AS "PLACE_OF_RECEIPT"
	, DLV.SHIPMENT_REFNUM_VALUE AS "PLACE_OF_DELIVERY"
	, ST.ACTUAL_ARRIVAL
	


FROM [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] R
JOIN [GLOGOWNERNA04PRD].[SHIPMENT_T] S
ON R.SHIPMENT_GID = S.SHIPMENT_GID
AND R.SHIPMENT_REFNUM_QUAL_GID = 'ILS.BILL_OF_LADING_NUMBER'
AND S.TRANSPORT_MODE_GID LIKE '%ILS.OCEAN%' 
JOIN GLOGOWNERNA04PRD.SHIPMENT_STOP_T ST
ON S.SHIPMENT_GID = ST.SHIPMENT_GID
    AND ST.STOP_NUM = '2'
LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] STC
ON R.SHIPMENT_GID = STC.SHIPMENT_GID
AND STC.SHIPMENT_REFNUM_QUAL_GID LIKE '%CASS_SENT_DATE%'

LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] DIS
ON R.SHIPMENT_GID = DIS.SHIPMENT_GID
AND DIS.SHIPMENT_REFNUM_QUAL_GID LIKE '%PORT_OF_DISCHARGE%'
--AND DIS.SHIPMENT_REFNUM_VALUE IS NULL

LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] LD
ON R.SHIPMENT_GID = LD.SHIPMENT_GID
AND LD.SHIPMENT_REFNUM_QUAL_GID LIKE '%PORT_OF_LOADING%'
--AND LD.SHIPMENT_REFNUM_VALUE IS NULL

LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] RCP
ON S.SHIPMENT_GID = RCP.SHIPMENT_GID
AND RCP.SHIPMENT_REFNUM_QUAL_GID LIKE '%PLACE_OF_RECEIPT%'
--AND RCP.SHIPMENT_REFNUM_VALUE IS NULL

LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] DLV
ON S.SHIPMENT_GID = DLV.SHIPMENT_GID
AND DLV.SHIPMENT_REFNUM_QUAL_GID LIKE '%PLACE_OF_DELIVERY%'
--AND DLV.SHIPMENT_REFNUM_VALUE IS NULL

WHERE SUBSTRING(S.DEST_LOCATION_GID, 6, 2) in ('US', 'MX', 'CA')
AND ST.ACTUAL_ARRIVAL LIKE '2023%'
AND STC.SHIPMENT_REFNUM_VALUE IS NULL