SELECT DISTINCT
    REPLACE(S.SHIPMENT_GID, 'ILS.', '') AS SHIPMENT_GID,
    ST.ACTUAL_ARRIVAL
FROM [GLOGOWNERNA04PRD].[SHIPMENT_T] S
LEFT JOIN [GLOGOWNERNA04PRD].[SHIPMENT_REFNUM_T] R
    ON S.SHIPMENT_GID = R.SHIPMENT_GID
    AND S.TRANSPORT_MODE_GID LIKE '%ILS.OCEAN%'
	AND R.SHIPMENT_REFNUM_QUAL_GID = 'ILS.CASS_SENT_DATE' 
JOIN [GLOGOWNERNA04PRD].[SHIPMENT_STOP_T] ST
    ON S.SHIPMENT_GID = ST.SHIPMENT_GID
    AND ST.STOP_NUM = '2'
WHERE SUBSTRING(S.DEST_LOCATION_GID, 6, 2) IN ('US', 'MX', 'CA')
    --AND ST.ACTUAL_ARRIVAL LIKE '2023%'
	AND ST.ACTUAL_ARRIVAL IS NOT NULL
	AND R.SHIPMENT_REFNUM_QUAL_GID IS NULL;